build: Use tsconfig.include to select files
Using wildcars like yarn run tsc src/**/* is non-portable, and it also
(accidentally) feeds JS files emitted in a previous build straight back
to TypeScript.

Incidentally, this also curbstomps compilation errors like:

  error TS2300: Duplicate identifier 'Element'

which was possibly caused by TypeScript confusing said interface with
the one defined in lib.dom.d.ts.